version: '3.1'

services:
  frontend-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/www/html:/app/dist
    command: sh -c "yarn install && yarn build"